//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatBot.Properties.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        internal static string L_UName {
            get {
                return ResourceManager.GetString("L_UName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Bot.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string TSDDB_Edit {
            get {
                return ResourceManager.GetString("TSDDB_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string TSDDB_File {
            get {
                return ResourceManager.GetString("TSDDB_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string TSDDB_Help {
            get {
                return ResourceManager.GetString("TSDDB_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string TSMI_About {
            get {
                return ResourceManager.GetString("TSMI_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Bot Mode.
        /// </summary>
        internal static string TSMI_BotMode {
            get {
                return ResourceManager.GetString("TSMI_BotMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Bot Chat.
        /// </summary>
        internal static string TSMI_CBChat {
            get {
                return ResourceManager.GetString("TSMI_CBChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string TSMI_Clear {
            get {
                return ResourceManager.GetString("TSMI_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command List.
        /// </summary>
        internal static string TSMI_CList {
            get {
                return ResourceManager.GetString("TSMI_CList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string TSMI_Copy {
            get {
                return ResourceManager.GetString("TSMI_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me Chat.
        /// </summary>
        internal static string TSMI_CUChat {
            get {
                return ResourceManager.GetString("TSMI_CUChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string TSMI_Cut {
            get {
                return ResourceManager.GetString("TSMI_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TSMI_Delete {
            get {
                return ResourceManager.GetString("TSMI_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TSMI_Exit {
            get {
                return ResourceManager.GetString("TSMI_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string TSMI_Lang {
            get {
                return ResourceManager.GetString("TSMI_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string TSMI_LangEnglish {
            get {
                return ResourceManager.GetString("TSMI_LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string TSMI_LangSpanish {
            get {
                return ResourceManager.GetString("TSMI_LangSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string TSMI_ModeHelp {
            get {
                return ResourceManager.GetString("TSMI_ModeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VS.
        /// </summary>
        internal static string TSMI_ModeVS {
            get {
                return ResourceManager.GetString("TSMI_ModeVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Conversation.
        /// </summary>
        internal static string TSMI_New {
            get {
                return ResourceManager.GetString("TSMI_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string TSMI_Paste {
            get {
                return ResourceManager.GetString("TSMI_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string TSMI_Preferences {
            get {
                return ResourceManager.GetString("TSMI_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string TSMI_Redo {
            get {
                return ResourceManager.GetString("TSMI_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string TSMI_SelectAll {
            get {
                return ResourceManager.GetString("TSMI_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string TSMI_Send {
            get {
                return ResourceManager.GetString("TSMI_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Log.
        /// </summary>
        internal static string TSMI_SLog {
            get {
                return ResourceManager.GetString("TSMI_SLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Name.
        /// </summary>
        internal static string TSMI_UCName {
            get {
                return ResourceManager.GetString("TSMI_UCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control with Microphone.
        /// </summary>
        internal static string TSMI_UCWMicro {
            get {
                return ResourceManager.GetString("TSMI_UCWMicro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string TSMI_Undo {
            get {
                return ResourceManager.GetString("TSMI_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string TSMI_User {
            get {
                return ResourceManager.GetString("TSMI_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string UB_Clear {
            get {
                return ResourceManager.GetString("UB_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string UB_Send {
            get {
                return ResourceManager.GetString("UB_Send", resourceCulture);
            }
        }
    }
}
